### ISSUE TITLE
Memory usage doesnt work on my env 

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/system-info#4]
Pluging works only without usage of mem_usage() .

See configuration
![image](https://user-images.githubusercontent.com/327030/104779298-efcc1000-578f-11eb-8d1e-893206d5cb6b.png)

If I added mem usage - trigger doesnot work

See examle rows from sysinfo tables
![image](https://user-images.githubusercontent.com/327030/104778998-5d2b7100-578f-11eb-8e07-8eb0e0b8acb6.png)

**Comment by AleksandrSokolov** [comment]
@glutamate I think that problem can be in node-os-utils dependency.

**Comment by glutamate** [comment]
@AleksandrSokolov yes i found a much better package for this: https://www.npmjs.com/package/systeminformation

**Comment by AleksandrSokolov** [comment]
@glutamate Great. Let me test when you change plugin

**Comment by glutamate** [comment]
this should be fixed in 0.1.2, which is based on systeminformation
